version: '3'
services:
  neo4j:
    image: neo4j:4.0.3
    hostname: neo4j
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./neo4j/plugins:/plugins
    environment:
      NEO4J_AUTH: neo4j/password
      NEO4J_ACCEPT_LICENSE_AGREEMENT: Y
      NEO4JLABS_PLUGINS: '["apoc"]'
  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "menome"
      RABBITMQ_DEFAULT_PASS: "menome"
  message-server:
    image: menome/message-server:latest
    ports:
      - "8081:8081"
    links:
      - rabbitmq
      - neo4j
    environment:
      RABBITMQ_HOST: "rabbitmq"
      NEO4J_HOST: "neo4j"
