endpoints:
  prometheus:
    sensitive: false
micronaut:
  application:
    name: messageServer
  metrics:
    enabled: true
    export:
      prometheus:
        enabled: true
        descriptions: true
        step: PT1M
  server:
    port: 8080
